### ISSUE TITLE
Carla ROS bridge failure

### ISSUE THREAD

**Issue by NeilNie** [laurent-george/carla#1]
Hello,

I was working with your `dev/add_ros_bridge` branch and the ROS bridge source code. I followed the README instructions and installed all the necessary dependencies. However, when I run the code with the following command: `roslaunch carla_ros_bridge client_with_rviz.launch`, I get the following error:

        assert len(raw_data) == 4 * width * height
    AssertionError

Here is the whole entire error message:

    [INFO] [1526329625.731374, 0.000000]: Trying to connect to localhost:2000
    [INFO] [1526329625.731779, 0.000000]: Connection is ok
    [INFO] [1526329625.743222, 0.000000]: Adding publisher for sensor camera_depth
    [INFO] [1526329625.746817, 0.000000]: Adding publisher for sensor CameraRGB
    [INFO] [1526329625.749244, 0.000000]: Adding publisher for sensor lidar_0
    [INFO] [1526329625.750340, 0.000000]: Adding publisher for sensor camera_semantic_segmentation
    [INFO] [1526329627.734084, 0.000000]: Exiting Bridge
    Traceback (most recent call last):
      File "/home/neil/Workspace/self-driving-golf-cart/src/carla_ros_bridge/src/client.py", line 553, in     <module>
        main()
      File "/home/neil/Workspace/self-driving-golf-cart/src/carla_ros_bridge/src/client.py", line 549, in main
        carla_ros_bridge.run()
      File "/home/neil/Workspace/self-driving-golf-cart/src/carla_ros_bridge/src/client.py", line 359, in run
        measurements, sensor_data = self.client.read_data()
      File "/usr/local/lib/python2.7/dist-packages/carla/client.py", line 127, in read_data
        return pb_message, dict(x for x in self._read_sensor_data())
      File "/usr/local/lib/python2.7/dist-packages/carla/client.py", line 127, in <genexpr>
        return pb_message, dict(x for x in self._read_sensor_data())
      File "/usr/local/lib/python2.7/dist-packages/carla/client.py", line 175, in _read_sensor_data
        yield self._parse_sensor_data(data)
      File "/usr/local/lib/python2.7/dist-packages/carla/client.py", line 180, in _parse_sensor_data
        return parser.name, parser.parse_raw_data(data[4:])
      File "/usr/local/lib/python2.7/dist-packages/carla/client.py", line 194, in parse_image
        return sensor.Image(width, height, image_type, fov, data[16:])
      File "/usr/local/lib/python2.7/dist-packages/carla/sensor.py", line 146, in __init__
        assert len(raw_data) == 4 * width * height
    AssertionError

Thanks for your time and attention. Thanks for the ROS bridge implemenation. Let me know if you need other details.

**Comment by aosmundson** [comment]
I'm having the same issue. Were you able to find a solution? Thanks

**Comment by NeilNie** [comment]
Hi, I did not find the complete solution to this problem. However, I did set up my own version of a very basic ROS bridge based on this code. You can find my version of the bridge [here](https://github.com/sigmaai/self-driving-golf-cart/tree/master/src/simulation). Please also note that my ROS bridge doesn't have any of the tf stuff. I am still trying to work on that.

**Comment by lgeo3** [comment]
Sorry guys, I haven't seen your problems/bug before. I am currently working on refactoring/cleaning the code today, so I will try to fix that.

**Comment by travelbureau** [comment]
I was having this problem also, I believe its because they did not rebuild carla from your dev/add_ros_bridge branch. I built the LinuxNoEditor binaries and it works fine now. Maybe they are using the binary from the regular carla release?

**Comment by travelbureau** [comment]
For me the call to start the carla server looks like this: 
`./Unreal/CarlaUE4/LinuxNoEditor/CarlaUE4.sh /Game/Maps/Town02 -carla-server -benchmark -fps=15 -windowed -ResX=320 -ResY=240`

**Comment by NeilNie** [comment]
@travelbureau do you mean that I have to build carla from the dev/add_ros_bridge? @laurent-george is it possible to update the ros_bridge code so that it works with the latest regular carla binary? Thanks!

**Comment by travelbureau** [comment]
Yes. I don't think it can work with the regular binary; however, @laurent-george currently has a pull request to incorporate the ros-bridge in the standard carla branch. Even then you would still have to build until they make a new release which I understand could be in a month or two. Anything in particular stopping your from building? Its not to bad using Ubuntu? Follow the instructions here: https://github.com/laurent-george/carla/tree/dev/add_ros_bridge/carla_ros_bridge

**Comment by lgeo3** [comment]
@NeilNie I have updated the dev/add_ros_bridge, now it works fine with the latest binary version: 0.8.2

I have updated the readme too, if you find mistake/things that could be improved please fill a bug report

**Comment by raulortiz8** [comment]
Hi, Laurent . I have a problem testing the instalation in running the test.
When I put this command:
rostest carla_ros_bridge ros_bridge_client.test
The next in my console is the following:
sas@sas-2:~$ rostest carla_ros_bridge ros_bridge_client.test
[ros_bridge_client.test] is neither a launch file in package [carla_ros_bridge] nor is [carla_ros_bridge] a launch file name
I hope you can help me.
Thanks in advance.

**Comment by lgeo3** [comment]
are you using the latest version merged in carla master ? (I was sure to have fix that problems..). A workaround is to go to the carla ros bridge directory and just use rostest ros_bridge_client.test  (let me know if it works for you )

**Comment by raulortiz8** [comment]
yes, I am using the lastest version of carla, what do you mean with just use ros_bridge_client.test. To open it?
Thanks in advance

**Comment by NeilNie** [comment]
@laurent-george I tested your latest ros bridge commit. Everything seems to be working fine, especially the rviz stuff. It looks great! Thanks a lot for the good work. @raulortiz8 did you do `source devel/setup.bash` ?

**Comment by lgeo3** [comment]
@raulortiz8 I mean just run: 

cd path_to_carla_ros_bridge
rostest ./ros_bridge_client.test 

but again, if you source your devel/setup.bash (from the catkin_workspace), everything should works fine as highlight by NeiNie.

So be sure to be running the latest version of carla_ros_bridge (not just carla), just pull/update the repo.

**Comment by minhaoxu1995** [comment]
Hi @laurent-george ,

I followed the set up instruction and when I run `rostest carla_ros_bridge ros_bridge_client.test`, there is a traceback saying
```
Traceback (most recent call last):
  File "/home/user/ros/catkin_ws_for_carla/src/carla_ros_bridge/src/carla_ros_bridge/client.py", line 8, in <module>
    from carla.client import make_carla_client
ModuleNotFoundError: No module named 'carla'
```
I am not quite sure what I did wrong in the former steps. In the install carla python client step, I create a folder `carla` under `~/ros/catkin_ws_for_carla` and copied `PythonClient` folder here. Then I can successfully import carla. I do not know why it fails when I run the test. Thanks!

version: carla 0.8.4

**Comment by lgeo3** [comment]
@minhaoxu1995
It seems that the python carla client is not installed in your python path.

Have you sourced the ~/ros/catkin_ws_for_carla ?
Which python version are you using ?
How have you installed the carla python client ? (using pip2 ?) The steps are: 

source ~/ros/catkin_ws_for_carla/devel/setup.bash
cd carla/PythonClient
pip2 install -e .  --user --upgrade   

then cd ~/ (just to be sure it works from any path).
python -c 'import carla;print("Success")'  <-- here you should get a Success (is it what you get ?)

**Comment by minhaoxu1995** [comment]
@laurent-george Thanks for replying! I tried again but it still does not work. 

alias python=python2
cd ~/
source ~/ros/catkin_ws_for_carla/devel/setup.bash
python -c 'import carla;print("Success")'
Success
python -V
Python 2.7.12
rostest carla_ros_bridge ros_bridge_client.test
... logging to /home/user/.ros/log/rostest-user-HP-Z640-Workstation-10684.log
[ROSUNIT] Outputting test results to /home/user/.ros/test_results/carla_ros_bridge/rostest-test_ros_bridge_client.xml
Traceback (most recent call last):
  File "/home/user/ros/catkin_ws_for_carla/src/carla_ros_bridge/src/carla_ros_bridge/client.py", line 8, in <module>
    from carla.client import make_carla_client
ModuleNotFoundError: No module named 'carla'

**Comment by NeilNie** [comment]
@minhaoxu1995 if you `cd carla/PythonClient` and then just do `sudo pip2 install .` it will install carla for all. This method worked for me.
