### ISSUE TITLE
cannot import "carla_server_pb2.py", run the protobuf compiler to generate this file

### ISSUE THREAD

**Issue by zhang261007** [laurent-george/carla#2]
raise RuntimeError('cannot import "carla_server_pb2.py", run '
RuntimeError: cannot import "carla_server_pb2.py", run the protobuf compiler to generate this file

 File "/home/zmr0almost/catkin_carla/src/carla_ros_bridge/src/client.py", line 22, in <module>
    from carla.client import make_carla_client
  File "/home/zmr0almost/carla/PythonClient/carla/client.py", line 14, in <module>
    from . import sensor
  File "/home/zmr0almost/carla/PythonClient/carla/sensor.py", line 19, in <module>
    from .transform import Transform, Translation, Rotation, Scale
  File "/home/zmr0almost/carla/PythonClient/carla/transform.py", line 20, in <module>
    raise RuntimeError('cannot import "carla_server_pb2.py", run '
RuntimeError: cannot import "carla_server_pb2.py", run the protobuf compiler to generate this file
[carla_ros_bridge-2] process has died [pid 8926, exit code 1, cmd /home/zmr0almost/catkin_carla/src/carla_ros_bridge/src/client.py __name:=carla_ros_bridge __log:=/home/zmr0almost/.ros/log/9c4fcd08-58c4-11e8-bbae-a0afbd9a4269/carla_ros_bridge-2.log].
log file: /home/zmr0almost/.ros/log/9c4fcd08-58c4-11e8-bbae-a0afbd9a4269/carla_ros_bridge-2*.log

is there any way to sovle these ?

**Comment by zhang261007** [comment]
RuntimeError: cannot import "carla_server_pb2.py", run the protobuf compiler to generate this file

try

sudo apt-get remove python-protobuf
sudo pip install --upgrade protobuf

**Comment by lgeo3** [comment]
@zhang261007  Are you still observing the issue ? could you try with latest branch modification (and latest readme/documentation ?

**Comment by lgeo3** [comment]
by the way, could you try:

sudo pip2 install --upgrade protobuf 

(seems like pip point to pip for python3 and ros is using python2.7 on default installation)

**Comment by lgeo3** [comment]
closing (no answer to question, please free to reopen if needed)
