### ISSUE TITLE
Carla ROS Bridge on ROS Indigo (APOLLO)

### ISSUE THREAD

**Issue by albe81x** [laurent-george/carla#4]
Hi George,
I am working on Carla and ROS Bridge. I would like to integrate an updated version of your Bridge inside a Docker. Unfortunately this Docker (coming from APOLLO platform) embeds an older version of ROS which is Indigo (2014) instead of ROS Kinetic. 
Do you think is it possible to make the ROS Bridge working on ROS Indigo inside a Docker? 

Many thanks for your support,
Regards
Alberto

**Comment by lgeo3** [comment]
I am quite sure that it will works with indigo (the bridge depends only on rosbag/messages/ and tf2) the kind of things that haven't change a lot since a long time.
